name: Build Yaml
on:
  push:
    branches: [ development-v0.2.0 ]
    paths:
      - '/contracts'
  pull_request:
    branches: [ development-v0.2.0 ]
    paths:
      - '/contracts'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx hardhat run scripts/deploy_all.js
